### ISSUE TITLE
add Info.OfFunctionPointer by OpCodes.Ldftn.

### ISSUE THREAD

**Issue by Dogwei** [Fody/InfoOf#278]
InfoOf is great!

If you can add 
```C#
IntPtr pFunc = Info.OfFunctionPointer("AssemblyName", "MyClass", "MyMethod");
```
it would be even cooler!

Use OpCodes.Ldftn instruction to achieve.

**Comment by ltrzesniewski** [comment]
I'm not sure if that would be a good fit for InfoOf, given that the result would be a pointer, not an "info" object.

You could wait for C# 9 which will expose function pointers, or use [InlineIL.Fody](https://github.com/ltrzesniewski/InlineIL.Fody) to write a method that uses `ldftn`.

**Comment by Dogwei** [comment]
Wow this is so cool, thank you!
