### ISSUE TITLE
Unhandled exception while weaving with built-in .NET types

### ISSUE THREAD

**Issue by DaleStan** [Fody/InfoOf#5]
A while ago, I wrote this code:

`Message m = (Message)typeof(OperationContext).InvokeMember("IncomingMessage", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.GetProperty, null, OperationContext.Current, null);`

I recognized it was fragile, but I couldn't come up with a better way to do it.
I recently found InfoOf.Fody, and figured I could change the code and get a compile error instead of a runtime error if the internal implementation of `OperationContext` changes:

`Message m = (Message)Info.OfPropertyGet("System.ServiceModel", "System.ServiceModel.OperationContext", "IncomingMessage").Invoke(OperationContext.Current, null);`

When I do this, though, I get this build output
`1>    Fody: Fody (version 1.29.4.0) Executing`
`1>      Fody/InfoOf:   	Removing reference to 'InfoOf.dll'.`
`1>MSBUILD : error : Fody: An unhandled exception occurred:`
`1>MSBUILD : error : Exception:`
`1>MSBUILD : error : Member 'System.ServiceModel.Channels.Message System.ServiceModel.OperationContext::get_IncomingMessage()' is declared in another module and needs to be imported`
`1>MSBUILD : error : StackTrace:`
`1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)`
`1>MSBUILD : error :    at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)`
`1>MSBUILD : error :    at Mono.Cecil.Cil.CodeWriter.WriteInstructions()`
`1>MSBUILD : error :    at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)`
`1>MSBUILD : error :    at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)`
`1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)`
`1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)`
`1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)`
`1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddTypeDefs()`
`1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.BuildTypes()`
`1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.BuildModule()`
`1>MSBUILD : error :    at Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _)`
`1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func3 read)`
`1>MSBUILD : error :    at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)`
`1>MSBUILD : error :    at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)`
`1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)`
`1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)`
`1>MSBUILD : error :    at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 18`
`1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 85`
`1>MSBUILD : error : Source:`
`1>MSBUILD : error : Mono.Cecil`
`1>MSBUILD : error : TargetSite:`
`1>MSBUILD : error : Mono.Cecil.MetadataToken LookupToken(Mono.Cecil.IMetadataTokenProvider)`
`1>MSBUILD : error : `
`1>    Fody:   Finished Fody 898ms.`

I have a reference to `System.ServiceModel` in my project, so that's not the issue. Am I doing something wrong in my `Info.OfPropertyGet` call? Or am I just missing some other reference? If the latter, what reference(s) am I missing?

**Comment by SimonCropp** [comment]
can u upload a repro?

**Comment by DaleStan** [comment]
I get the exception when building this solution, in both the Debug and Release builds. I'm still using Visual Studio 2015, in case that makes a difference.
[InfoOfTest.zip](https://github.com/Fody/InfoOf/files/961582/InfoOfTest.zip)

**Comment by DaleStan** [comment]
Have you had any luck with that repro? I tried again with Fody 2.0.9 and InfoOf 1.1.0 (which seem to be the latest available on NuGet) and I'm getting the same exception.

**Comment by jasonwoods-7** [comment]
Looks like this may be the same issue as I reported in my PR #6.

**Comment by SimonCropp** [comment]
this is now deployed
