### ISSUE TITLE
Parameter with nested namespaces proposal

### ISSUE THREAD

**Issue by jasonwoods-7** [Fody/InfoOf#585]
#### You should already be a Patron

I am a Patron

#### Is the proposal related to a problem

It seems odd that when specifying arguments to methods that only the top-level namespace is removed to check whether the type matches.

The example given in the readme:

Nested namespaces are not handled, only `"Regex"` won't work, but `"System.Text.RegularExpressions.Regex"` or `"Text.RegularExpressions.Regex"`.

It seems like this should be updated to accept simply `Regex` instead of `Text.RegularExpressions.Regex`.

#### Describe the solution

To solve this, we could simply change [line 14 of TypeReferenceExtensions.cs](https://github.com/Fody/InfoOf/blob/991a4a2227b8a5533f997aec31fcea8115c616a3/InfoOf.Fody/TypeReferenceExtensions.cs#L14) from

```csharp
var dotIndex = fullName.IndexOf('.');
```

to

```csharp
var dotIndex = fullName.LastIndexOf('.');
```

This would be a breaking change, so I'm raising this as a proposal to get input to see whether this change should be made or not.

**Comment by SimonCropp** [comment]
@jasonwoods-7  happy for the breaking change. just need to document it.

do u want to do the PR?

**Comment by jasonwoods-7** [comment]
after doing some work on this, this case is already handled by [this check](https://github.com/Fody/InfoOf/blob/991a4a2227b8a5533f997aec31fcea8115c616a3/InfoOf.Fody/TypeReferenceExtensions.cs#L10)

guess i was just confused by the documentation. not sure what test case the check to take off the first part of the namespace was added for, so i'll just leave as is.
